import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { format } from 'prettier';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = (file) => readFile(path.join(root, file), 'utf8');
const lock = JSON.parse(await read('package-lock.json'));
const packages = Object.entries(lock.packages)
  .filter(([directory]) => directory)
  .sort(([a], [b]) => a.localeCompare(b, 'en'));
const packageName = (directory) => directory.split('node_modules/').at(-1);
const sourceLink = (directory, entry) =>
  `https://www.npmjs.com/package/${packageName(directory)}/v/${entry.version}`;

let runtime = `Third-party notices for rainy-running-simulator\n\n`;
runtime += `Original project code is licensed under MIT; see LICENSE.txt.\nThird-party components retain their own copyrights and licenses.\nThe following texts are copied from the installed packages without modification.\n\n`;
for (const [directory, entry] of packages.filter(([, entry]) => !entry.dev)) {
  const license = await read(`${directory}/LICENSE`);
  runtime += `${packageName(directory)} ${entry.version} (${entry.license})\n${sourceLink(directory, entry)}\n\n${license}\n\n`;
}
let inventory = `# Third-party notices\n\n`;
inventory += `This file is generated by \`npm run licenses\` from package-lock.json and installed runtime licenses. Original project code is licensed under [MIT](LICENSE). Third-party components retain their own licenses; the project license does not relicense them.\n\n`;
inventory += `Full copyright and license texts for runtime dependencies are distributed in [public/THIRD_PARTY_NOTICES.txt](public/THIRD_PARTY_NOTICES.txt). Both this file and [public/LICENSE.txt](public/LICENSE.txt) are included in the static website.\n\n`;
inventory += `## Locked dependency inventory\n\nThe inventory includes runtime, development, transitive, and optional platform packages. A lockfile entry does not imply that the package is included in the browser bundle. Version links identify the upstream packages and their license declarations. Development tools keep the license files supplied with their packages in node_modules; those tools are not distributed as part of the website.\n\n`;
inventory += `| Package | Version | License | Usage |\n| --- | --- | --- | --- |\n`;
for (const [directory, entry] of packages) {
  if (!entry.license)
    throw new Error(`Missing license declaration: ${directory}`);
  inventory += `| [${packageName(directory)}](${sourceLink(directory, entry)}) | ${entry.version} | ${entry.license} | ${entry.dev ? 'Development' : 'Runtime'}${entry.optional ? ' (optional)' : ''} |\n`;
}
inventory += `\n## Research reference\n\nFranco Bocci, “Whether or not to run in the rain” (2012), [DOI: 10.1088/0143-0807/33/5/1321](https://doi.org/10.1088/0143-0807/33/5/1321), is a research reference. The paper is linked, not reproduced or relicensed under this project's MIT license. The simulation and wet-area approximation are implemented independently in this project.\n`;
await writeFile(path.join(root, 'public/LICENSE.txt'), await read('LICENSE'));
await writeFile(path.join(root, 'public/THIRD_PARTY_NOTICES.txt'), runtime);
await writeFile(
  path.join(root, 'THIRD_PARTY_NOTICES.md'),
  await format(inventory, { parser: 'markdown', singleQuote: true }),
);
console.log(
  `Generated license notices for ${packages.length} locked packages.`,
);
